service: translation-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 256
  httpApi:
    cors: false
    authorizers:
      telegramWebhookAuthorizer:
        type: request
        functionName: TelegramWebhookAuthorizer
        identitySource:
          - $request.header.x-telegram-bot-api-secret-token
        payloadVersion: "1.0"
        enableSimpleResponses: false
  logs:
    httpApi:
      format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","routeKey":"$context.routeKey", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength", "authorizerError": "$context.authorizer.error" }'


package:
 patterns:
   - "!node_modules/**"
   - "!*.template"
   - "!package-lock.json"
   - "!package.json"
   - "*.rb"
   - config.yml

functions:
  TelegramWebhookAuthorizer:
    handler: telegram_webhook_authorizer.authorize
  HandleTelegramMessage:
    handler: handle_telegram_message.handle
    events:
      - httpApi:
          path: /handle-message
          method: POST
          authorizer:
            name: telegramWebhookAuthorizer
  TranslateMessage:
    handler: translate_message.chatgpt_translate
  RespondToTelegram:
    handler: respond_to_telegram.send_message
stepFunctions:
  stateMachines:
    TranslationBot:
      name: TranslationBot
      definition:
        StartAt: TranslateMessageState
        States:
          TranslateMessageState:
            Type: Task
            Resource:
              Fn::GetAtt: [TranslateMessage, Arn]
            Next: RespondToTelegramState
          RespondToTelegramState:
            Type: Task
            Resource:
              Fn::GetAtt: [RespondToTelegram, Arn]
            End: true
  validate: true

plugins:
  - serverless-step-functions
