service: translation-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby3.2
  memorySize: 256
  httpApi:
    cors: false
    authorizers:
      telegramWebhookAuthorizer:
        type: request
        functionName: TelegramWebhookAuthorizer
        identitySource:
          - $request.header.x-telegram-bot-api-secret-token
        payloadVersion: "2.0"
        enableSimpleResponses: true
  logs:
    httpApi:
      format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","routeKey":"$context.routeKey", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength", "authorizerError": "$context.authorizer.error" }'
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'states:StartExecution'
          Resource:
            Fn::Join:
              - ''
              - - 'arn:aws:states:'
                - Ref: AWS::Region
                - ':'
                - Ref: AWS::AccountId
                - ':stateMachine:TranslationBot'

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!*"
    - config.yml

functions:
  TelegramWebhookAuthorizer:
    handler: telegram_webhook_authorizer.authorize
    package:
      patterns:
        - telegram_webhook_authorizer.rb
  IngestTelegramWebhook:
    handler: ingest_telegram_webhook.handle
    package:
      patterns:
        - ingest_telegram_webhook.rb
    environment:
      TRANSLATION_BOT_STATE_MACHINE_ARN:
        Fn::GetAtt: [TranslationBot, Arn]
    events:
      - httpApi:
          path: /handle-message
          method: POST
          authorizer:
            name: telegramWebhookAuthorizer
  ProcessIncomingMessage:
    handler: process_incoming_message.handle
    package:
      patterns:
        - process_incoming_message.rb
  TranslateMessage:
    handler: translate_message.chatgpt_translate
    package:
      patterns:
        - translate_message.rb
  TranslationErrorHandler:
    handler: translate_message.handle_translation_failure
    package:
      patterns:
        - translate_message.rb
  RespondToTelegram:
    handler: respond_to_telegram.send_message
    package:
      patterns:
        - respond_to_telegram.rb
stepFunctions:
  stateMachines:
    TranslationBot:
      name: TranslationBot
      definition:
        StartAt: ProcessIncomingMessageState
        States:
          ProcessIncomingMessageState:
            Type: Task
            Resource:
              Fn::GetAtt: [ProcessIncomingMessage, Arn]
            Next: CheckIfTranslateRequiredState
          CheckIfTranslateRequiredState:
            Type: Choice
            Choices:
              - Variable: "$.message_to_translate"
                IsPresent: true
                Next: TranslateMessageState
            Default: CheckIfReplyRequiredState
          TranslateMessageState:
            Type: Task
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 10
                MaxAttempts: 2
                BackoffRate: 2.0
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: TranslationErrorHandlerState
                ResultPath: "$.error"
            Resource:
              Fn::GetAtt: [TranslateMessage, Arn]
            Next: CheckIfReplyRequiredState
          TranslationErrorHandlerState:
            Type: Task
            Resource:
              Fn::GetAtt: [TranslationErrorHandler, Arn]
            Next: CheckIfReplyRequiredState
          CheckIfReplyRequiredState:
            Type: Choice
            Choices:
              - Variable: "$.message_to_send"
                IsPresent: true
                Next: RespondToTelegramState
            Default: EndExecution
          RespondToTelegramState:
            Type: Task
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 10
                MaxAttempts: 2
                BackoffRate: 2.0
            Resource:
              Fn::GetAtt: [RespondToTelegram, Arn]
            End: true
          EndExecution:
            Type: Succeed
  validate: true

plugins:
  - serverless-step-functions
